services:
  api:
    build: .
    container_name: authictator-api
    env_file: .env
    ports:
      - "${PORT}:3000"
    command: npm run start
    volumes:
      - .:/app 
      - /app/node_modules
    environment:
      NODE_ENV: development
      DATABASE_URL: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:${DATABASE_PORT}/${DATABASE_NAME}?authSource=admin
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:7
    container_name: authictator-db
    restart: unless-stopped
    ports:
      - "${DATABASE_PORT}:27017"
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo-data:/data/db

  redis:
    build:
      context: ./redis
      dockerfile: Dockerfile
    container_name: authictator-cache
    restart: unless-stopped
    ports:
      - "${REDIS_PORT}:6379"
    env_file: .env
    environment:
      - REDIS_WRITER_PASSWORD=${REDIS_WRITER_PASSWORD}
      - REDIS_READER_PASSWORD=${REDIS_READER_PASSWORD}
    volumes:
      - redis-data:/data
      - ./redis/users-template.acl:/usr/local/etc/redis/users-template.acl
    entrypoint: ["/usr/local/bin/redis-entrypoint.sh"]

volumes:
  mongo-data:
  redis-data:

